import { Montserrat, Anonymous_Pro } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const anonymousPro = Anonymous_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-anonymous-pro",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${anonymousPro.variable} dark font-sans antialiased bg-background overflow-x-hidden`} style={{ scrollSnapType: 'y mandatory', scrollBehavior: 'smooth' }}>   
          <Navbar />
          <main className="flex-1 min-w-0">{children}</main>
      </body>
    </html>
  );
}
